version: '3'

services:

  golang_app:
    image: golang:1.12-alpine
    container_name: golang
    volumes:
      - ./5000:/5000
    working_dir: /5000
    command: >
      sh -c "go build uno.go && ./uno"
    expose:
      - "5000"


  php-apache1:
    image: php:8.2-apache
    container_name: php-apache1
    volumes:
      - ./80:/var/www/html
    expose:
      - 80

  php-apache2:
    image: php:8.2-apache
    container_name: php-apache2
    volumes:
      - ./80:/var/www/html
    expose:
      - 80

  nginx:
    image: nginx:1.28.0
    container_name: nginx-balancer
    ports:
      - "8080:80"
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./demo.com.crt:/etc/nginx/ssl/demo.com.crt
      #- ./demo.com.key:/etc/nginx/ssl/demo.com.key
    depends_on:
      - php-apache1
      - php-apache2
      - golang_app
